version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  dbNumber3:
    image: mongo
    ports:
      - "27017:27017"
  dbNumber4:
    image: mongo
    ports:
      - "27017:27017"
  dbNumber44222211:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - "db"
    environment:
      - MONGODB_HOST=db
