version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "80:80"
    links:
      - "db"
    environment:
      - MONGODB_HOST=db
      - PORT=80
    depends_on:
      - db
